//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodDatabaseEntities : DbContext
    {
        public FoodDatabaseEntities()
            : base("name=FoodDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fs_admin> fs_admin { get; set; }
        public virtual DbSet<fs_category> fs_category { get; set; }
        public virtual DbSet<fs_restaurant> fs_restaurant { get; set; }
        public virtual DbSet<fs_user> fs_user { get; set; }
        public virtual DbSet<fs_item> fs_item { get; set; }
        public virtual DbSet<fs_order> fs_order { get; set; }
    }
}
