//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class fs_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fs_admin()
        {
            this.fs_restaurant = new HashSet<fs_restaurant>();
        }
    
        public int a_id { get; set; }

        [Required (ErrorMessage = "Required Field"), DisplayName ("User Name")]
        public string a_username { get; set; }

        [Required(ErrorMessage = "Required Field"), DisplayName("Password")]
        public string a_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fs_restaurant> fs_restaurant { get; set; }
    }
}
