//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class fs_dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fs_dish()
        {
            this.fs_order = new HashSet<fs_order>();
        }
    
        public int d_id { get; set; }
        public string d_image { get; set; }
        public Nullable<int> d_res_id { get; set; }
        public Nullable<int> d_user_id { get; set; }
        public string d_name { get; set; }
    
        public virtual fs_restaurant fs_restaurant { get; set; }
        public virtual fs_user fs_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fs_order> fs_order { get; set; }
    }
}
