//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class fs_order
    {
        public int o_id { get; set; }
        public Nullable<int> o_res_id { get; set; }
        public Nullable<int> o_dish_id { get; set; }
        public string o_dish_name { get; set; }
        public string o_location { get; set; }
        public Nullable<System.DateTime> o_time { get; set; }
    
        public virtual fs_dish fs_dish { get; set; }
        public virtual fs_restaurant fs_restaurant { get; set; }
    }
}
