//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class fs_order
    {
        [DisplayName("Order ID")]
        public int o_id { get; set; }

        [DisplayName("User ID")]
        public Nullable<int> o_u_id { get; set; }

        [DisplayName("Item ID")]
        public Nullable<int> o_i_id { get; set; }

        [DisplayName("Order Total")]
        public Nullable<int> o_total { get; set; }

        [DisplayName("Contact")]
        public string o_contact { get; set; }

        [DisplayName("Address")]
        public string o_address { get; set; }

        [DisplayName("Order Date")]
        public Nullable<System.DateTime> o_date { get; set; }
    
        public virtual fs_item fs_item { get; set; }
        public virtual fs_user fs_user { get; set; }
    }
}
